// <auto-generated />
namespace RentYourCar_PWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlgueresStateFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlgueresStateFK));
        
        string IMigrationMetadata.Id
        {
            get { return "201808141109367_AlgueresStateFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
