// <auto-generated />
namespace RentYourCar_PWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlgueresStatePOP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlgueresStatePOP));
        
        string IMigrationMetadata.Id
        {
            get { return "201808141120196_AlgueresStatePOP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
